{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nextcloud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" (dict "root" . "tenant" nil) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nextcloud.serviceAccountName" . }}-scc-anyuid
  labels:
    {{- include "nextcloud.labels" (dict "root" . "tenant" nil) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
  - kind: ServiceAccount
    name: {{ include "nextcloud.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}